<?php

return[

	'beancounter'	=> env('EVE_PROCESSING_BEANCOUNTER'		, 4	),
	'station_tax'	=> env('EVE_PROCESSING_STATION_TAX'		, 1.00	),
	'station_yield'	=> env('EVE_PROCESSING_STATION_YIELD'		, 0.52	),
	'reprocessing'	=> env('EVE_PROCESSING_REPROCESSING'		, 5	),
	'efficiency'	=> env('EVE_PROCESSING_REPROCESSING_EFFICIENCY'	, 5	),
	'ice'		=> env('EVE_PROCESSING_ICE'			, 5	),
	'scrapmetal'	=> env('EVE_PROCESSING_SCRAPMETAL'		, 5	),
	'arkonor'	=> env('EVE_PROCESSING_ARKONOR'			, 5	),
	'bistot'	=> env('EVE_PROCESSING_BISTOT'			, 5	),
	'crokite'	=> env('EVE_PROCESSING_CROKITE'			, 5	),
	'dark_ochre'	=> env('EVE_PROCESSING_DARK_OCHRE'		, 5	),
	'gneiss'	=> env('EVE_PROCESSING_GNEISS'			, 5	),
	'hedbergite'	=> env('EVE_PROCESSING_HEDBERGITE'		, 5	),
	'hemorphite'	=> env('EVE_PROCESSING_HEMORPHITE'		, 5	),
	'jaspet'	=> env('EVE_PROCESSING_JASPET'			, 5	),
	'kernite'	=> env('EVE_PROCESSING_KERNITE'			, 5	),
	'mercoxit'	=> env('EVE_PROCESSING_MERCOXIT'		, 5	),
	'omber'		=> env('EVE_PROCESSING_OMBER'			, 5	),
	'plagioclase'	=> env('EVE_PROCESSING_PLAGIOCLASE'		, 5	),
	'pyroxeres'	=> env('EVE_PROCESSING_PYROXERES'		, 5	),
	'scordite'	=> env('EVE_PROCESSING_SCORDITE'		, 5	),
	'spodumain'	=> env('EVE_PROCESSING_SPODUMAIN'		, 5	),
	'veldspar'	=> env('EVE_PROCESSING_VELDSPAR'		, 5	),
	'bitumens'	=> env('EVE_PROCESSING_BITUMENS'		, 5	),
	'coesite'	=> env('EVE_PROCESSING_COESITE'			, 5	),
	'sylvite'	=> env('EVE_PROCESSING_SYLVITE'			, 5	),
	'zeolites'	=> env('EVE_PROCESSING_ZEOLITES'		, 5	),
	'cobaltite'	=> env('EVE_PROCESSING_COBALTITE'		, 5	),
	'euxenite'	=> env('EVE_PROCESSING_EUXENITE'		, 5	),
	'scheelite'	=> env('EVE_PROCESSING_SCHEELITE'		, 5	),
	'titanite'	=> env('EVE_PROCESSING_TITANITE'		, 5	),
	'chromite'	=> env('EVE_PROCESSING_CHROMITE'		, 5	),
	'otavite'	=> env('EVE_PROCESSING_OTAVITE'			, 5	),
	'sperrylite'	=> env('EVE_PROCESSING_SPERRYLITE'		, 5	),
	'vanadinite'	=> env('EVE_PROCESSING_VANADINITE'		, 5	),
	'carnotite'	=> env('EVE_PROCESSING_CARNOTITE'		, 5	),
	'cinnabar'	=> env('EVE_PROCESSING_CINNABAR'		, 5	),
	'pollucite'	=> env('EVE_PROCESSING_POLLUCITE'		, 5	),
	'zircon'	=> env('EVE_PROCESSING_ZIRCON'			, 5	),
	'loparite'	=> env('EVE_PROCESSING_LOPARITE'		, 5	),
	'monazite'	=> env('EVE_PROCESSING_MONAZITE'		, 5	),
	'xenotime'	=> env('EVE_PROCESSING_XENOTIME'		, 5	),
	'ytterbite'	=> env('EVE_PROCESSING_YTTERBITE'		, 5	),

];
